### ISSUE TITLE
Dublicate records

### ISSUE THREAD

**Issue by rmalenko** [ghoneycutt/puppet-module-hosts#76]
My hosts.yaml is
```
---
classes:
  - hosts

hosts::host_entries:
  'clickhouse-001-01.biz':
    ip: '1.230.22.175'
    host_aliases:
      - 'clickhouse-001-01'

  'clickhouse-001-02.biz':
    ip: '1.230.99.211'
    host_aliases:
      - 'clickhouse-001-02'

  'clickhouse-002-01.biz':
    ip: '1.230.99.212'
    host_aliases:
      - 'clickhouse-002-01'

  'clickhouse-002-02.biz':
    ip: '1.230.99.214'
    host_aliases:
      - 'clickhouse-002-02'

```

and it creates this hosts file

```
# HEADER: This file was autogenerated at 2019-03-14 14:27:58 +0000
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.
127.0.0.1	localhost.localdomain	localhost localhost4 localhost4.localdomain4
::1	localhost6.localdomain6	localhost6 localhost6.localdomain6
1.230.22.175	clickhouse-001-01	clickhouse-001-01
1.230.22.175	clickhouse-001-01.biz	clickhouse-001-01
1.230.99.211	clickhouse-001-02.biz	clickhouse-001-02
1.230.99.212	clickhouse-002-01.biz	clickhouse-002-01
1.230.99.214	clickhouse-002-02.biz	clickhouse-002-02
```

I think the line insn't necesarry.
`1.230.22.175	clickhouse-001-01	clickhouse-001-01`
